# .github/workflows/deploy.yml
name: Deploy 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'bump version')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          service_account_email: "github-actions@resolute-radar-357007.iam.gserviceaccount.com"
          project_id: resolute-radar-357007

      - name: Building
        run: |-
          gcloud builds submit \
            --tag gcr.io/resolute-radar-357007/continous-deployment

      # Setup gcloud CLI
      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: continous-deployment
          image: gcr.io/resolute-radar-357007/continous-deployment
          region: us-east1
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: resolute-radar-357007
